[package]

name = "filestore"
version = "0.1.1"
authors = ["Mike Dilger <mike@efx.co.nz>"]
license = "MIT"

[features]
default = [ "rustc-serialize", "serde", "serde_macros" ]

[dependencies.postgres]
version = ">= 0.11.11, < 0.12"

[dependencies]
log = "0.3"
byteorder = "0.4"
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "0.8", optional = true }
serde_macros = { version = "0.8", optional = true }
rust-crypto = "0.2"
clippy = { version = "0.0", optional = true }
