[package]

name = "filestore"
version = "0.1.1"
authors = ["Mike Dilger <mike@efx.co.nz>"]
license = "MIT"

[features]
default = [ "serde", "serde_derive", "postgres" ]

[dependencies]
log = "0.3"
byteorder = "1.0.0"
rustc-serialize = { version = "0.3", optional = true }
serde = { version = "0.9", optional = true }
serde_derive = { version = "0.9", optional = true }
rust-crypto = "0.2"
clippy = { version = "0.0", optional = true }
postgres = { version = "0.14", optional = true }
phf_codegen = "0.7"
